export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#1a0600',
        'primary-fixed-dim': '#aec7f6',
        'surface-dim': '#d8dadc',
        'on-primary': '#ffffff',
        surface: '#f7f9fb',
        'on-secondary-fixed': '#1b1c1c',
        'on-tertiary-container': '#e16300',
        'surface-container-low': '#f2f4f6',
        'primary-fixed': '#d6e3ff',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        outline: '#74777f',
        'tertiary-fixed-dim': '#ffb690',
        'on-tertiary-fixed': '#341100',
        'on-primary-container': '#708ab5',
        'inverse-surface': '#2d3133',
        'tertiary-container': '#3d1600',
        'surface-variant': '#e0e3e5',
        'surface-container-high': '#e6e8ea',
        secondary: '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e3e2e2',
        primary: '#000a1e',
        background: '#f7f9fb',
        'on-primary-fixed-variant': '#2d476f',
        'outline-variant': '#c4c6cf',
        'tertiary-fixed': '#ffdbca',
        'on-surface-variant': '#44474e',
        'on-secondary-container': '#646464',
        'primary-container': '#002147',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#464747',
        'surface-bright': '#f7f9fb',
        'on-tertiary-fixed-variant': '#783200',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'secondary-fixed': '#e3e2e2',
        'on-primary-fixed': '#001b3d',
        'on-background': '#191c1e',
        'surface-tint': '#465f88',
        'on-error-container': '#93000a',
        'inverse-primary': '#aec7f6',
        'error-container': '#ffdad6',
        'secondary-fixed-dim': '#c7c6c6',
        'surface-container': '#eceef0',
        'industrial-orange': '#e16300',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '16px',
        md: '24px',
        'margin-mobile': '16px',
        lg: '48px',
        xs: '8px',
        gutter: '24px',
        base: '4px',
        xl: '80px',
        'container-max': '1280px',
      },
      fontFamily: {
        'label-caps': ['Inter', 'sans-serif'],
        'headline-xl': ['Montserrat', 'sans-serif'],
        'headline-sm': ['Montserrat', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-xl-mobile': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
